---
- name: Create directories for strongswan
  ansible.builtin.file: 
    path: "{{ item }}"
    state: directory
    mode: '0750'
    owner: root
    group: root
  with_items:
    - /etc/ipsec.conf.d
    - /etc/ipsec.secrets.d
    - /var/log/strongswan

- name: Copy strongswan configuration file(s)
  ansible.builtin.template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart strongswan service

- name: Copy strongswan secret file(s)
  ansible.builtin.template:
    src: ipsec.secrets.j2
    dest: /etc/ipsec.secrets
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart strongswan service

- name: Configuring logging for strongswan charon
  ansible.builtin.template:
    src: charon-logging.conf.j2
    dest: /etc/strongswan.d/charon-logging.conf
    mode: '0644'
    owner: root
    group: root
  with_items: "{{ strongswan_logs | default([]) }}"

- name: Activate logrotate for strongswan charon
  ansible.builtin.blockinfile:
    create: true
    block: |
      /var/log/strongswan/*.log {
              daily
              missingok
              rotate 7
              compress
              compresscmd /usr/bin/pigz
              delaycompress
              notifempty
              create 640 root adm
              sharedscripts
              postrotate
                      [ -f /var/run/charon.pid ] && kill -HUP `cat /var/run/charon.pid`
              endscript
      }
    path: /etc/logrotate.d/charon
    mode: '0640'
    owner: root
    group: root

- name: Enable packages gather facts
  ansible.builtin.package_facts:
    manager: auto

- name: Add apparmor local rules (skip if apparmor isn't installed)
  when: "'apparmor' in ansible_facts.packages"
  ansible.builtin.template:
    src: usr.lib.ipsec.charon.j2
    dest: /etc/apparmor.d/local/usr.lib.ipsec.charon
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload apparmor service

- name: Add sysctl entry for ipforward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    sysctl_file: /etc/sysctl.d/50_ipforward.conf
    value: '1'
    sysctl_set: true
    reload: true

- name: Add Let's Encrypt CA cert for strongswan
  ansible.builtin.get_url:
    url: https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
    dest: /etc/ipsec.d/cacerts/lets-encrypt-x3-cross-signed.pem
    mode: '0644'
    owner: root
    group: root
