---
- name: Restart strongswan service
  ansible.builtin.service:
    name: ipsec
    state: restarted

- name: Reload strongswan service
  ansible.builtin.service:
    name: ipsec
    state: reloaded

- name: Rereadsecrets of strongswan service
  ansible.builtin.command: ipsec rereadsecrets
  changed_when: false

- name: Reload apparmor service
  ansible.builtin.service:
    name: apparmor
    state: reloaded
